name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
        -
            name: Checkout
            uses: actions/checkout@v4
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
        -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
            name: Generate Release
            id: release
            env:
                GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            uses: rymndhng/release-on-push-action@master
            with:
              bump_version_scheme: minor
              use_github_release_notes: true
              tag_prefix: v
        -
            name: Build and push
            id: build
            uses: docker/build-push-action@v5
            with:
                context: .
                platforms: linux/amd64,linux/arm64
                push: true
                tags: ${{ github.repository }}:latest, ${{ github.repository }}:${{steps.release.outputs.version}}
        -
            name: Update repo description
            uses: peter-evans/dockerhub-description@v3
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                repository: ${{ github.repository }}
        -
            name: Success Discord Notification
            if: success()
            uses: rjstone/discord-webhook-notify@v1
            with:
                severity: info
                details: Sucesso no build!
                username: Octocat
                avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
                webhookUrl: ${{secrets.DISCORD_WEBHOOK}}
        -
            name: Failure Discord Notification
            if: failure()
            uses: rjstone/discord-webhook-notify@v1
            with:
                severity: error
                details: ${{ join(steps.build.outputs.*, '\n') }}
                username: Octocat
                avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
                webhookUrl: ${{secrets.DISCORD_WEBHOOK}}